Merge 'apple' branch with 'master' branch.
paulgureghian/Apple.com pull request #1
Opened 2019-10-07 00:48 UTC by paulgureghian

2019-10-07 05:27 UTC, whiz25 requested changes
## Good job with the project @paulgureghian :+1: 
However, the project is still far from being merged. There are a lot of changes to be made. Please look at my suggestions below;
- [ ] add a navbar with 9 buttons. the navbar should be implemented with ```background -> gradient ```
- [ ] include a footer wrapped in ```<footer>``` tag
- [ ] your page should also include four elements with links
- [ ] make your clone as close to the original page as possible. Check the original site [here](https://web.archive.org/web/20140301004610/http://www.apple.com/)

### Please make those changes and re-submit for another review.

2019-10-07 23:09 UTC, Redvanisation requested changes
### Hello @paulgureghian 🌟

**Good work on this project, but we need to fix the issues below before moving on ⬇️** 

1. Your CSS file is empty, please implement and apply the necessary styles.

2. The `<link>` tag has an error, see my comment below and fix it.

3. Please Validate and fix the HTML markup [here](https://validator.w3.org/#validate_by_input)

4. Make the README file more descriptive, check [this](https://github.com/othneildrew/Best-README-Template) link for reference.

### _After making the required changes please submit a new code review request_

### Good luck! 🍀

2019-10-07 23:09 UTC, Redvanisation commented on index.html
> +  <link href="styles.css type=" text/css" rel="stylesheet">
You have an error on here, please link the CSS file properly

2019-10-09 00:11 UTC, stratospherique requested changes
> #### Pull request under review by Ahmed Mahfoudh (TSE)

### Hi @paulgureghian 

- I still cannot find the content of your _styles.css_ file and the live preview also shows an un-styled webpage.

- **[REQUIRED]** refer to the comments of the reviewer above :arrow_up: . They should guide you through getting your project approved.

### that's it :relieved: . When finished, kindly resubmit another code review request :pray:

2019-10-09 20:41 UTC, Redvanisation requested changes
### Hello @paulgureghian 

### _Well done correcting the HTML markup, however you still have some issues that need to be fixed before I can approve the project:_ 

1. Your CSS file has only one class, please fill-up the styles needed for this project and push it to your repo before submitting a new code review request, this is how the website is looking on my screen (it needs to be looking exactly like the original website): 
<img width="645" alt="Screen Shot 2019-10-09 at 4 36 14 PM" src="https://user-images.githubusercontent.com/33462180/66518483-5eadba00-eab3-11e9-8d15-c99f68b60c68.png">


2. Make the README file more descriptive, check [this](https://github.com/othneildrew/Best-README-Template) link for reference.

- If you need help with that you can reach out to me on slack: **_@redvan_**

### _After making the required changes please submit a new code review request_

### Good luck! 🍀

2019-10-10 01:08 UTC, Redvanisation requested changes
### Hello @paulgureghian 

**Good work so far but the project is still not looking like the original website, please refer to the page original page in [here](https://web.archive.org/web/20140301004610/http://www.apple.com/) and try to style your project according to it.**

### _After making the required changes please submit a new code review request_

### Good luck! 🍀

2019-10-21 21:14 UTC, ebukaume commented
# Changes required! :stop_sign: 
Hi @paulgureghian :wave: 

Please make the requested changes. You can start by first making the image a background image. You can refer to [this article](https://css-tricks.com/almanac/properties/b/background-image/). 

Then read about how to use flexbox [here](https://css-tricks.com/snippets/css/a-guide-to-flexbox/). With these, you can achieve most of the desired result.

**Kindly submit another code review when your page looks like the one [here](https://web.archive.org/web/20140301004610/http://www.apple.com/)**


Happy Coding :v: 
**Ebuka Umeokonkwo**
 [Github](https://github.com/ebukaume) | [Linkedin](https://www.linkedin.com/in/ebukaume) | [Slack](https://app.slack.com/team/UFDKXE68L) | [Twitter](https://twitter.com/ebukaume)

2019-10-21 21:22 UTC, paulgureghian commented
Can I ask you a question here ?

2019-10-21 22:04 UTC, ebukaume commented
> Can I ask you a question here ?

Yes, please.

2019-10-21 22:41 UTC, paulgureghian commented
<nav id="globalheader" class="apple">
    <ul id="globalnav" role="navigation">
        <li id="gn-apple"><a href="https://web.archive.org/web/20140301004610/http://www.apple.com/"><span>Apple</span></a></li>
        <li id="gn-store"><a href="https://web.archive.org/web/20140301004610/http://store.apple.com/"><span>Store</span></a></li>
        <li id="gn-mac"><a href="https://web.archive.org/web/20140301004610/http://www.apple.com/mac/"><span>Mac</span></a></li>
        <li id="gn-ipod"><a href="https://web.archive.org/web/20140301004610/http://www.apple.com/ipod/"><span>iPod</span></a></li>
        <li id="gn-iphone"><a href="https://web.archive.org/web/20140301004610/http://www.apple.com/iphone/"><span>iPhone</span></a></li>
        <li id="gn-ipad"><a href="https://web.archive.org/web/20140301004610/http://www.apple.com/ipad/"><span>iPad</span></a></li>
        <li id="gn-itunes"><a href="https://web.archive.org/web/20140301004610/http://www.apple.com/itunes/"><span>iTunes</span></a></li>
        <li id="gn-support" class="gn-last"><a href="https://web.archive.org/web/20140301004610/http://www.apple.com/support/"><span>Support</span></a></li>

2019-10-21 22:43 UTC, paulgureghian commented
<nav id="globalheader" class="apple">
    <ul id="globalnav" role="navigation">
        <li id="gn-apple"><a href="https://web.archive.org/web/20140301004610/http://www.apple.com/"><span>Apple</span></a></li>
        <li id="gn-store"><a href="https://web.archive.org/web/20140301004610/http://store.apple.com/"><span>Store</span></a></li>
        <li id="gn-mac"><a href="https://web.archive.org/web/20140301004610/http://www.apple.com/mac/"><span>Mac</span></a></li>
        <li id="gn-ipod"><a href="https://web.archive.org/web/20140301004610/http://www.apple.com/ipod/"><span>iPod</span></a></li>
        <li id="gn-iphone"><a href="https://web.archive.org/web/20140301004610/http://www.apple.com/iphone/"><span>iPhone</span></a></li>
        <li id="gn-ipad"><a href="https://web.archive.org/web/20140301004610/http://www.apple.com/ipad/"><span>iPad</span></a></li>
        <li id="gn-itunes"><a href="https://web.archive.org/web/20140301004610/http://www.apple.com/itunes/"><span>iTunes</span></a></li>
        <li id="gn-support" class="gn-last"><a href="https://web.archive.org/web/20140301004610/http://www.apple.com/support/"><span>Support</span></a></li>

2019-10-21 22:43 UTC, paulgureghian commented
`            <nav id="globalheader" class="apple">
    <ul id="globalnav" role="navigation">
        <li id="gn-apple"><a href="https://web.archive.org/web/20140301004610/http://www.apple.com/"><span>Apple</span></a></li>
        <li id="gn-store"><a href="https://web.archive.org/web/20140301004610/http://store.apple.com/"><span>Store</span></a></li>
        <li id="gn-mac"><a href="https://web.archive.org/web/20140301004610/http://www.apple.com/mac/"><span>Mac</span></a></li>
        <li id="gn-ipod"><a href="https://web.archive.org/web/20140301004610/http://www.apple.com/ipod/"><span>iPod</span></a></li>
        <li id="gn-iphone"><a href="https://web.archive.org/web/20140301004610/http://www.apple.com/iphone/"><span>iPhone</span></a></li>
        <li id="gn-ipad"><a href="https://web.archive.org/web/20140301004610/http://www.apple.com/ipad/"><span>iPad</span></a></li>
        <li id="gn-itunes"><a href="https://web.archive.org/web/20140301004610/http://www.apple.com/itunes/"><span>iTunes</span></a></li>
        <li id="gn-support" class="gn-last"><a href="https://web.archive.org/web/20140301004610/http://www.apple.com/support/"><span>Support</span></a></li>
                                 `

2019-10-21 22:44 UTC, paulgureghian commented
Shouldnt the text in the span tags actually render on the navbar buttons ?

2019-10-21 23:03 UTC, ebukaume commented
> Shouldnt the text in the span tags actually render on the navbar buttons ?

They should and they do. The problem is with the styles you applied. Have you considered using button tags? It would be much simpler `<button>Button Name</button>`.

2019-10-23 05:09 UTC, suretrust commented
**Great job @paulgureghian. :+1:** 

The clone doesn't look much like [this](https://web.archive.org/web/20140301004610/http://www.apple.com/)

Please take your time and go at your pace, look at the page you want to clone. Inspect the page using developer tools if necessary, then go ahead to start cloning. You can read [this article](https://www.lifewire.com/web-browser-developer-tools-3988965) to know how to use developer tools.

Also, be sure to have no linter error when submitting another code review. 

_Overall, I love your tenacity, keep up the great work!_

**Kindly re-submit for another code review once you have fixed these issues. Good luck! :tada:**

2019-11-14 02:37 UTC, Redvanisation requested changes
# Changes required  ♻️ 

**Excellent work so far, but we need to fix the issues below before moving on ⬇️** 

1. Please fix the search bar in the nav, I left a comment on how to do so below.

2. Delete the duplication in the main text, see my comment below about that.

3. Fix Stickler errors on the project, it has to be green before the project can be approved.

4. Please Validate and fix the HTML markup [here](https://validator.w3.org/#validate_by_input)

### _After making the required changes please submit a new code review request_

### Good luck! 🍀

2019-11-14 02:37 UTC, Redvanisation commented on index.html
> +			<li id="search"></li>
The search bar should be an `<input type="text" class="search">` then style the class search in the CSS file,  and not a CSS image

2019-11-14 02:37 UTC, Redvanisation commented on index.html
> +			 <img src="images/cta_your_verse_27pt.png" alt="cta"/>
The text is duplicated here please fix that

2019-11-14 02:37 UTC, Redvanisation commented on styles.css
> +div {
Delete the whitespaces after the `div {`

2019-11-14 02:37 UTC, Redvanisation commented on styles.css
> +  margin-top: 3px;
Delete the whitespaces after the `3px;`

2019-11-14 20:43 UTC, Anna-Myzukina commented
#### Pull Request under the review by Anna Muzykina (TSE)

2019-11-14 21:35 UTC, Anna-Myzukina commented
### Hi Paul! ![](https://user-images.githubusercontent.com/38801423/62908122-703d4480-bd44-11e9-9115-42025ab7f341.png) 
#### Wow, your project looks :+1: 
#### But need some Required Changes

### Page structure

#### Navbar

- [ ] It should be made of nine different buttons with the Apple logo on the leftmost section and a search field on the rightmost section

*** Now your search field is under other buttons, but it should be on the rightmost section. Please fix this***
![search](https://user-images.githubusercontent.com/26605804/68896739-d024fc00-0734-11ea-94b9-4032d1bf816a.png)

#### Bottom

* [ ] It contains four elements which are links (to another articles or `#`)

*** This elements should be links ***
![links](https://user-images.githubusercontent.com/26605804/68897146-8dafef00-0735-11ea-9307-54c495a27861.png)

Please delete h2 Promos inside section class="down" you don`t need it
*** With this element ***
![before](https://user-images.githubusercontent.com/26605804/68897909-1e3aff00-0737-11ea-8940-e35098e8e441.png)

*** Without this element ***
![after](https://user-images.githubusercontent.com/26605804/68897932-2a26c100-0737-11ea-94d6-631812d2feff.png)


Your README.md file descriptive, but if you want you can use this short [Markdown Cheatsheet](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet) to make this file more professional.

Great that you use [`<nav>` tag](http://html5doctor.com/nav-element/) for the major navigation links and the [`<footer>`](https://www.w3schools.com/TagS/tag_footer.asp) tag for the footer, but not bad to use the [`<main>` tag](https://www.w3schools.com/tags/tag_main.asp) for the dominant content of the `<body>` of a document.


### Make changes and submit another code review request.

*If you have any questions, let me know on slack (@Anna-Muzykina) and I will be glad to clarify with you.*
*Happy coding 😄*

2019-11-14 21:38 UTC, Anna-Myzukina commented on index.html
> +
It should be on the rightmost section

2019-11-14 21:41 UTC, Anna-Myzukina commented on index.html
> +	<h2>Promos</h2>
Please delete <h2>Promos</h2> you don`t need this element

2019-11-14 21:44 UTC, Anna-Myzukina commented on index.html
> +	<h2>Promos</h2>
Please delete h2 Promos, you don`t need this element.

2019-11-14 21:46 UTC, Anna-Myzukina commented on index.html
> +	</div>
This elements should be links

2019-11-14 21:48 UTC, Anna-Myzukina commented on index.html
> +			 <form action="https://web.archive.org/web/20140301004315/http://www.apple.com//search/" method="POST" class="search" id="g-search">
It should be on the rightmost section

2019-11-14 21:51 UTC, Anna-Myzukina requested changes
The project still needs changes

2019-11-15 04:42 UTC, suretrust requested changes
Hi @paulgureghian,

### Amazing job thus far, :raised_hands: the images and background sections are lit! Just one more thing to go. Please see my comments on your code.

**Kindly submit for another code review once this has been fixed.** _Happy coding!_ :tada:

2019-11-15 04:42 UTC, suretrust commented on index.html
> +			 <form action="https://web.archive.org/web/20140301004315/http://www.apple.com//search/" method="POST" class="search" id="g-search">
Your navbar gradient design and placement still don't look close to the original website. Kindly fix.

**Yours**
![nav](https://user-images.githubusercontent.com/31304943/68917339-1ea0bd80-076a-11ea-9433-0ddf044d4a20.png)
**Original**
![nav2](https://user-images.githubusercontent.com/31304943/68917359-2e200680-076a-11ea-8d45-9678629b98d8.png)

2019-11-16 02:04 UTC, imhta approved these changes
# Project Approved 👏
Hello @paulgureghian, Congratulations you have done great job. 



<img src="https://thumbs.gfycat.com/SpeedyAmazingIndianpalmsquirrel-size_restricted.gif">


----
#### Don't forgot to sumbit project completion form
 **Pon Muthu Selvam N**
Feel free contact me 
[Github //@imhta](https://github.com/imhta) | [Twitter //@nponmuthuselvam](https://twitter.com/ponmuthuselvam)

2019-11-16 03:36 UTC, merged